import { createMulterOptions } from '@fitfriends/core';
import {
  AVATAR_FILE_MAX_SIZE,
  AVATAR_FILE_TYPE_REGEXP,
  CERTIFICATE_FILE_MAX_SIZE,
  CERTIFICATE_FILE_TYPE_REGEXP,
  GYM_PHOTO_FILE_MAX_COUNT,
  GYM_PHOTO_FILE_MAX_SIZE,
  GYM_PHOTO_FILE_TYPE_REGEXP,
  TRAINING_MOVIE_FILE_MAX_SIZE,
  TRAINING_MOVIE_FILE_TYPE_REGEXP,
} from '../app/app.constant';

export const MulterOptions = {
  Avatar: createMulterOptions(AVATAR_FILE_MAX_SIZE, AVATAR_FILE_TYPE_REGEXP),
  Certificate: createMulterOptions(CERTIFICATE_FILE_MAX_SIZE, CERTIFICATE_FILE_TYPE_REGEXP),
  GymPhotos: createMulterOptions(GYM_PHOTO_FILE_MAX_SIZE, GYM_PHOTO_FILE_TYPE_REGEXP, GYM_PHOTO_FILE_MAX_COUNT),
  TrainingMovie: createMulterOptions(TRAINING_MOVIE_FILE_MAX_SIZE, TRAINING_MOVIE_FILE_TYPE_REGEXP),
} as const;
